```{r setup, include=FALSE}
library(tidyverse)
library(here)
library(webchem)
library(clusterProfiler)
library(org.Hs.eg.db)
library(dplyr)
library(conflicted)
library(fst)
library(ChemmineR)
library(VennDiagram)
library(wesanderson)
conflicts_prefer(select::dplyr)
conflicts_prefer(clusterProfiler::select)
conflicts_prefer(clusterProfiler::rename)
conflicts_prefer(clusterProfiler::filter)
conflicts_prefer(base::setdiff)
```

# processing kinobeads data

## new kuster data
```{r}
kuster <- read_csv(here("data/new_kuster_data/kds.csv"))
kuster_compound_info_tool = read_csv(here("data/new_kuster_data/compound_info.csv"))
kuster_compound_info_clinical = read_csv(here("data/new_kuster_data/compound_info_clinical.csv"))

kuster_compound_info = bind_rows(kuster_compound_info_tool, kuster_compound_info_clinical  %>% rename(Compound = Drug))  %>% 
    select(Compound, SMILES)

kuster_compound_cid = get_cid(unique(kuster_compound_info$SMILES), from = "smiles", domain = "compound", match = "all", verbose = T)

kuster_compound_info = kuster_compound_info  %>% 
    left_join(kuster_compound_cid, by = c("SMILES" = "query"))  %>% 
    select(Compound, SMILES, cid)

kuster_processed = kuster  %>% 
    rename(Kinase = `Gene name`, Kd = `apparent Kd`)  %>% 
    left_join(kuster_compound_info, by = "Compound")  %>% 
    select(Kinase, Compound, SMILES, cid, Kd) %>%
    filter(!is.na(Kd))
```

# processing klaeger data
```{r}

klaeger_compound_info = read_csv(here("data/klaeger_data/klaeger_compound_info.csv"))  %>% 
    select(Compound = Drug, SMILES = `SMILES code`, cid = PubChemCID)

klaeger_processed = read_csv(here("data/klaeger_data/apparent_kd_values.csv"))  %>% 
    select(Compound = Drug, Kinase = Target, Kd = At)  %>% 
    left_join(klaeger_compound_info, by = "Compound")
```

# processing LINCS data
```{r}

kinomescan_protein_info = read_csv(here("data/okl_profiling_data/eurofins_kinase_info.csv"))

LINCS_processed = read_csv(here("data/LINCS_data/LINCS_KINOMEscan_Kd.csv"))  %>% 
    select(Kinase = `Protein Name`, Compound = `Small Molecule Name`, Kd)  %>% 
    filter(!is.na(Kd))  %>% 
    left_join(kinomescan_protein_info  %>% select(`DiscoveRx Gene Symbol`, `Entrez Gene Symbol`), by = c("Kinase" = "DiscoveRx Gene Symbol"))  %>%
    rename(entrez_gene_symbol = `Entrez Gene Symbol`) 

```

# processing OKL data
```{r}

okl_compound_info = read_fst(here("data/okl_profiling_data/lsp_compound_dictionary.fst"))  %>% 
    select(Compound = pref_name, inchi)  %>% 
    distinct()  %>%
    drop_na()

okl_processed = read_csv(here("data/okl_profiling_data/okl_eurofins_pseudo_ic50.csv")) %>% 
    select(Kinase = `DiscoveRx Gene Symbol`, Compound = name, Kd = pseudo_ic50, entrez_gene_symbol = `Entrez Gene Symbol`)  %>% 
    left_join(okl_compound_info, by = "Compound")

okl_cid = pubchemInchi2cid(okl_processed$inchi  %>% unique())

okl_processed_compound_info = okl_processed  %>% 
    select(Compound, inchi)  %>%
    distinct()  %>% 
    bind_cols(cid = okl_cid)

okl_processed = okl_processed  %>% 
    left_join(okl_processed_compound_info, by = "Compound")  %>% 
    select(Kinase, Compound, Kd, entrez_gene_symbol, cid)

```

# Use bitr to convert gene symbols to entrez gene ids for all datasets
```{r}
kuster_entrez = bitr(kuster_processed$Kinase, fromType = "SYMBOL", toType = "ENTREZID", OrgDb = org.Hs.eg.db)

kuster_processed_entrez = kuster_processed  %>% 
    left_join(kuster_entrez, by = c("Kinase" = "SYMBOL"))  %>% 
    select(Kinase, Compound, SMILES, Kd, ENTREZID, cid)

klaeger_entrez = bitr(klaeger_processed$Kinase, fromType = "SYMBOL", toType = "ENTREZID", OrgDb = org.Hs.eg.db)

klaeger_processed_entrez = klaeger_processed  %>% 
    left_join(klaeger_entrez, by = c("Kinase" = "SYMBOL"))  %>% 
    select(Kinase, Compound, Kd, ENTREZID, cid)

LINCS_entrez = bitr(LINCS_processed$entrez_gene_symbol, fromType = "SYMBOL", toType = "ENTREZID", OrgDb = org.Hs.eg.db)

LINCS_processed_entrez = LINCS_processed  %>% 
    left_join(LINCS_entrez, by = c("entrez_gene_symbol" = "SYMBOL"))  %>% 
    select(Kinase, Compound, Kd, ENTREZID)

okl_entrez = bitr(okl_processed$entrez_gene_symbol, fromType = "SYMBOL", toType = "ENTREZID", OrgDb = org.Hs.eg.db)

okl_processed_entrez = okl_processed  %>% 
    left_join(okl_entrez, by = c("entrez_gene_symbol" = "SYMBOL"))  %>% 
    select(Kinase, Compound, Kd, ENTREZID, cid)

```

# CIDs for all datasets
```{r}
devtools::install_github("karthik/wesanderson")_processed_entrez  %>% 
    select(Kinase, Compound, Kd, ENTREZID, cid)  %>% 
    mutate(dataset = "klaeger", cid = as.character(cid))

LINCS_cids = get_cid(unique(LINCS_processed_entrez$Compound), from = "name", domain = "compound", match = "all", verbose = T)

LINCS_entrez_cid = LINCS_processed_entrez  %>% 
    left_join(LINCS_cids, by = c("Compound" = "query"))  %>% 
    select(Kinase, Compound, Kd, ENTREZID, cid)  %>% 
    mutate(dataset = "LINCS", cid = as.character(cid))

okl_entrez_cid = okl_processed_entrez  %>% 
    select(Kinase, Compound, Kd, ENTREZID, cid)  %>% 
    mutate(dataset = "okl", cid = as.character(cid))

```

# Combine all datasets
```{r}
combined_dataset = bind_rows(kuster_entrez_cid, klaeger_entrez_cid, LINCS_entrez_cid, okl_entrez_cid)  %>%  
    select(Kinase, Compound, Kd, ENTREZID, cid, SMILES, dataset)
```

# Venn diagram of compounds in each dataset
```{r}

# Split the dataset by the 'dataset' column to get unique compounds from each original dataset
datasets_split <- split(combined_dataset, combined_dataset$dataset)

# Get unique compounds for each dataset
unique_compounds <- lapply(datasets_split, function(df) unique(df$Compound))

# Prepare a named list for VennDiagram (assuming you have 4 datasets)
list_for_venn <- setNames(unique_compounds, names(unique_compounds))

#use wesanderson palette
myCol <- wes_palette("Zissou1", 4)

# Generate and plot the Venn diagram (for 4 datasets, a quad Venn diagram)
venn.plot <- venn.diagram(
  x = list_for_venn,
  filename = here("figures/venn_diagram_kd_data.png"),
  category.names = names(list_for_venn),
  output = TRUE,
    # Output features
    imagetype="png" ,
    height = 1480 , 
    width = 1480 , 
    resolution = 300,
  #plot features
  lwd = 2,
  lty = "blank",
  fill = myCol,
  cex = .6,
  fontface = "bold",
  fontfamily = "sans"
)

dev.off()  # This turns off the current device. You may need to run it multiple times.

# Display the Venn Diagram
grid.draw(venn.plot)
```